/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package patstake1;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;

/**
 *
 * @author YishaiBasserabie
 */
public class addLessonForm extends javax.swing.JFrame {

    String lessonKey;
    
    /**
     * Creates new form addLessonForm
     */
    public addLessonForm() {
        initComponents();
        populateComboBoxes pop = new populateComboBoxes();
        
        this.studentsAddedList.removeAll(); //removes generic items from studentsAddedList
        this.addStudentNameComboBox.removeAllItems();//removes all generic tiems from name combo box
        
        //populates grade combo box
        DefaultComboBoxModel grades = new DefaultComboBoxModel(pop.populateGrades());
        this.addStudentGradeComboBox.setModel(grades);
        //populates venues combo box
        DefaultComboBoxModel venues = new DefaultComboBoxModel(pop.populateVenues());
        this.addVenueComboBox.setModel(venues);
        //populates duration spinner with hour options
        SpinnerListModel hours = new SpinnerListModel(pop.populateDurationSpinner());
        this.durationSpinner.setModel(hours);
        
        //generates the lesson key for lesson to be added
        lessonDataArray la = new lessonDataArray();
        this.lessonKey = la.generateLessonKey();
        System.out.println(this.lessonKey);
    }
    //list model
    DefaultListModel StudentsAddedListModel = new DefaultListModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addlessonLabel = new javax.swing.JLabel();
        backToDashboardButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsAddedList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        addStudentGradeComboBox = new javax.swing.JComboBox<>();
        addStudentNameComboBox = new javax.swing.JComboBox<>();
        addLessonTimeHourComboBox = new javax.swing.JComboBox<>();
        addVenueComboBox = new javax.swing.JComboBox<>();
        addStudentToLessonButton = new javax.swing.JButton();
        addLessonButton = new javax.swing.JButton();
        deleteStudentFromLessonButton = new javax.swing.JButton();
        addDateComboBox = new com.toedter.calendar.JDateChooser();
        addLessonTimeMinuteComboBox = new javax.swing.JComboBox<>();
        frequencyComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        durationSpinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addlessonLabel.setText("add lesson!");

        backToDashboardButton.setText("back");
        backToDashboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("venue");

        jLabel4.setText("lesson date");

        jLabel5.setText("lesson time");

        jLabel6.setText("students added:");

        jScrollPane1.setViewportView(studentsAddedList);

        jLabel1.setText("add student:");

        jLabel2.setText("grade");

        jLabel7.setText("name");

        addStudentGradeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));
        addStudentGradeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentGradeComboBoxActionPerformed(evt);
            }
        });

        addStudentNameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addLessonTimeHourComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24" }));
        addLessonTimeHourComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonTimeHourComboBoxActionPerformed(evt);
            }
        });

        addVenueComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        addVenueComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVenueComboBoxActionPerformed(evt);
            }
        });

        addStudentToLessonButton.setText("add student");
        addStudentToLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentToLessonButtonActionPerformed(evt);
            }
        });

        addLessonButton.setText("add lesson!");
        addLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLessonButtonActionPerformed(evt);
            }
        });

        deleteStudentFromLessonButton.setText("delete student");
        deleteStudentFromLessonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentFromLessonButtonActionPerformed(evt);
            }
        });

        frequencyComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "once off", "weekly", "monthly" }));
        frequencyComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frequencyComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Duration(hours):");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backToDashboardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addlessonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addLessonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addVenueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(addStudentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(addStudentGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(addStudentToLessonButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteStudentFromLessonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addLessonTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(addLessonTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(frequencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(durationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(114, 114, 114))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addlessonLabel)
                    .addComponent(backToDashboardButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(addStudentGradeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(addStudentNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(addStudentToLessonButton)
                                            .addComponent(deleteStudentFromLessonButton)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(durationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(addVenueComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addDateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frequencyComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addLessonTimeHourComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addLessonTimeMinuteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(addLessonButton)
                .addGap(125, 125, 125))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentToLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentToLessonButtonActionPerformed
        ConnectDB db = new ConnectDB();
        String name = this.addStudentNameComboBox.getSelectedItem().toString();
        lessonDataArray la = new lessonDataArray();
        la.addToNamesList(this.addStudentNameComboBox.getSelectedItem().toString());
        for (int i = 0; i < la.getNames().size(); i++) {
            StudentsAddedListModel.addElement(la.getArrayOfStudentsAdded(i));
        }
        this.studentsAddedList.setModel(StudentsAddedListModel);
    }//GEN-LAST:event_addStudentToLessonButtonActionPerformed
    //TODO: make seperate class for this
    private void addStudentGradeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentGradeComboBoxActionPerformed
        ConnectDB db = new ConnectDB();
        studentsArray sa = new studentsArray();
        populateComboBoxes pop = new populateComboBoxes();
        //populates students combo box according to grade selected
        this.addStudentNameComboBox.removeAllItems();
        DefaultComboBoxModel correctedStudents = new DefaultComboBoxModel(pop.correctStudentsAccordingToGrade(this.addStudentGradeComboBox.getSelectedItem().toString()));
        this.addStudentNameComboBox.setModel(correctedStudents);
    }//GEN-LAST:event_addStudentGradeComboBoxActionPerformed
//TODO: fix the deletion and validation
    private void deleteStudentFromLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentFromLessonButtonActionPerformed
        lessonDataArray la = new lessonDataArray();
        la.removeStudentAdded(this.studentsAddedList.getSelectedValue());
        System.out.println("selected: " + this.studentsAddedList.getSelectedValue());
        this.StudentsAddedListModel.removeAllElements();
        for (int i = 0; i < la.getNames().size(); i++) {
            StudentsAddedListModel.addElement(la.getArrayOfStudentsAdded(i));
        }
        this.studentsAddedList.setModel(StudentsAddedListModel);
    }//GEN-LAST:event_deleteStudentFromLessonButtonActionPerformed

    private void addVenueComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVenueComboBoxActionPerformed
        
    }//GEN-LAST:event_addVenueComboBoxActionPerformed

    private void addLessonTimeHourComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonTimeHourComboBoxActionPerformed
        populateComboBoxes pop = new populateComboBoxes();
        //populates minute combo box according to hour selected
        this.addLessonTimeMinuteComboBox.removeAllItems();//removes previously generated items in minute combo box
        DefaultComboBoxModel minutes = new DefaultComboBoxModel(pop.populateMinuteComboBoxAccordingToHour(this.addLessonTimeHourComboBox.getSelectedItem().toString()));
        this.addLessonTimeMinuteComboBox.setModel(minutes);
    }//GEN-LAST:event_addLessonTimeHourComboBoxActionPerformed

    private void addLessonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLessonButtonActionPerformed
        lessonDataArray la = new lessonDataArray();
        //gets and formats date
        String time = this.addLessonTimeMinuteComboBox.getSelectedItem().toString();
        String date = la.formatDate(this.addDateComboBox.getDate().toString());
        String day = la.formatDay(this.addDateComboBox.getDate().toString());
        //pushes lesson
        for (int i = 0; i < this.StudentsAddedListModel.size(); i++) {
            System.out.println("");
            la.addLesson(this.addVenueComboBox.getSelectedItem().toString(), 
                    la.formatDate(this.addDateComboBox.getDate().toString()), 
                    this.addLessonTimeMinuteComboBox.getSelectedItem().toString(), 
                    la.formatDay(this.addDateComboBox.getDate().toString()), 
                    this.StudentsAddedListModel.size(), 
                    this.StudentsAddedListModel.get(i).toString(), this.frequencyComboBox.getSelectedIndex(),
                    Integer.parseInt(this.durationSpinner.getValue().toString()), this.lessonKey);
        }
        la.sortArray();
        this.hide();
    }//GEN-LAST:event_addLessonButtonActionPerformed

    private void backToDashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardButtonActionPerformed
        dashboard d = new dashboard();
        lessonDataArray la = new lessonDataArray();
        la.sortArray();
        d.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backToDashboardButtonActionPerformed

    private void frequencyComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frequencyComboBoxActionPerformed
        
    }//GEN-LAST:event_frequencyComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addLessonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addLessonForm().setVisible(true);
            }
        });
    }

    public JComboBox<String> getAddLessonTimeHourComboBox() {
        return addLessonTimeHourComboBox;
    }

    public JComboBox<String> getAddLessonTimeMinuteComboBox() {
        return addLessonTimeMinuteComboBox;
    }

    public JComboBox<String> getAddStudentGradeComboBox() {
        return addStudentGradeComboBox;
    }

    public JComboBox<String> getAddStudentNameComboBox() {
        return addStudentNameComboBox;
    }

    public JComboBox<String> getAddVenueComboBox() {
        return addVenueComboBox;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser addDateComboBox;
    private javax.swing.JButton addLessonButton;
    private javax.swing.JComboBox<String> addLessonTimeHourComboBox;
    private javax.swing.JComboBox<String> addLessonTimeMinuteComboBox;
    private javax.swing.JComboBox<String> addStudentGradeComboBox;
    private javax.swing.JComboBox<String> addStudentNameComboBox;
    private javax.swing.JButton addStudentToLessonButton;
    private javax.swing.JComboBox<String> addVenueComboBox;
    private javax.swing.JLabel addlessonLabel;
    private javax.swing.JButton backToDashboardButton;
    private javax.swing.JButton deleteStudentFromLessonButton;
    private javax.swing.JSpinner durationSpinner;
    private javax.swing.JComboBox<String> frequencyComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> studentsAddedList;
    // End of variables declaration//GEN-END:variables
}
